name: Build Launcher Templates

on:
  push:
    paths:
      - 'templates/launcher_template.py'
      - '.github/workflows/build_launcher_templates.yml'
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-windows:
    name: Build Windows Template
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows template
        run: |
          pyinstaller --clean --onefile --windowed --icon=resources/icons/app_icon.png --name=launcher_template_windows templates/launcher_template.py

      - name: Move built template
        run: |
          mv dist/launcher_template_windows.exe templates/bin/

      - name: Upload template artifact
        uses: actions/upload-artifact@v4
        with:
          name: launcher-template-windows
          path: templates/bin/launcher_template_windows.exe
          retention-days: 1

  build-linux:
    name: Build Linux Template
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install dependencies needed for PyQt5
          sudo apt-get update
          sudo apt-get install -y libxcb-xinerama0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xkb1 libxkbcommon-x11-0 libxcb-shape0

      - name: Build Linux template
        run: |
          pyinstaller --clean --onefile --windowed --icon=resources/icons/app_icon.png --name=launcher_template_linux templates/launcher_template.py

      - name: Move built template
        run: |
          mv dist/launcher_template_linux templates/bin/

      - name: Upload template artifact
        uses: actions/upload-artifact@v4
        with:
          name: launcher-template-linux
          path: templates/bin/launcher_template_linux
          retention-days: 1

  build-macos:
    name: Build macOS Template
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build macOS template
        run: |
          pyinstaller --clean --onefile --windowed --icon=resources/icons/app_icon.png --name=launcher_template_macos templates/launcher_template.py

      - name: Move built template
        run: |
          mv dist/launcher_template_macos templates/bin/

      - name: Upload template artifact
        uses: actions/upload-artifact@v4
        with:
          name: launcher-template-macos
          path: templates/bin/launcher_template_macos
          retention-days: 1

  commit-templates:
    name: Commit Template Executables
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'  # Only run on direct pushes, not PRs
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Windows template
        uses: actions/download-artifact@v4
        with:
          name: launcher-template-windows
          path: templates/bin

      - name: Download Linux template
        uses: actions/download-artifact@v4
        with:
          name: launcher-template-linux
          path: templates/bin

      - name: Download macOS template
        uses: actions/download-artifact@v4
        with:
          name: launcher-template-macos
          path: templates/bin

      - name: Make templates executable
        run: |
          chmod +x templates/bin/launcher_template_linux
          chmod +x templates/bin/launcher_template_macos

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit templates
        run: |
          git add templates/bin/launcher_template_windows.exe
          git add templates/bin/launcher_template_linux
          git add templates/bin/launcher_template_macos
          git commit -m "Update launcher templates [skip ci]" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}